apiVersion: apps/v1
kind: Deployment
metadata:
  name: war-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: war-web
  template:
    metadata:
      labels:
        app: war-web
    spec:
      containers:
      - name: war-web
        image: wardaddyov/war-web:dev
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: war-web-service
spec:
  selector:
    app: war-web
  ports:
  - port: 80
    targetPort: 80
